# **NUMPY**

In [1]:
# numpy means Numerical Python. when we deal with arrays and numbers in python then we use 'numpy' library
import numpy as np

In [2]:
# we can create array using list
simple_list=[6,7,8]
np.array(simple_list)

array([6, 7, 8])

In [3]:
# we can create array by defing it in a variable.
arr=np.array([ 9201, 7864, 2351])
arr

array([9201, 7864, 2351])

In [4]:
# we can create a multi dimensional array like this.
# but when we create multi dimensional array using list we have to put all the lists in large brackets.
multi_dim_arr=[['mayank',21,'bahjoi'],['abhay',20,'amroha'],['mukul',22,'rampur']]
np.array(multi_dim_arr)

array([['mayank', '21', 'bahjoi'],
       ['abhay', '20', 'amroha'],
       ['mukul', '22', 'rampur']], dtype='<U21')

In [5]:
np.arange(10,21)
# this method is used to print number b/w (arg1) and ((arg2)-1)
# in this method (arg1) is the first value of the output, this method given

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [6]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(5,45,6)
# in this method '5' is the first number, '45' will be the last number but we have another argument i.e., 6,
# it means every number in the output will have the difference of '6'.
# hence in the below output every number has the difference of '6' and last number is based on the difference.
# or we can say that thee last argument in the above method is the 'step size of the numbers.'

array([ 5, 11, 17, 23, 29, 35, 41])

In [8]:
np.arange(10)
# in this method we only have 1 argument i.e., 10. we seek help in notebook by pressing 'shift + tab'. it shows a help box of
# the specific thing in the code by which we can understand what does that thing work.
# here, in this method by taking help, we understand that "if only argument is here then the first default value is 0."

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.zeros(5)
# this method prints the zeros with floating point jitne argument mein diye hotey hain.

array([0., 0., 0., 0., 0.])

In [10]:
np.zeros(6, int)
# if we specify the datatype then it prints accordingly.

array([0, 0, 0, 0, 0, 0])

In [11]:
np.zeros((2,3))
# by this, we can print array in 2D format with floating point. In this the Ist arg would be no. of rows and
# IInd arg would be no. of colulmns.

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
np.zeros((5,5),int)
# by this, we can print 2D array in integer format.

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [13]:
np.ones(6)
# this prints ones with floating point.

array([1., 1., 1., 1., 1., 1.])

In [14]:
np.ones((3,7),int)
# all properties same as zeros.

array([[1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1]])

In [15]:
np.linspace(1,12,6)
# linspace is a method which equally divides the numbers based on its last argument.
# generated output would have 1st and 2nd argument same but the number of output digits would depends on last argument.

array([ 1. ,  3.2,  5.4,  7.6,  9.8, 12. ])

In [16]:
np.linspace(7,38,3)

array([ 7. , 22.5, 38. ])

In [17]:
np.eye(18, dtype=int)
# '.eye()' method gives us a identity matrix of n X n elements in which diognal elements are only ones and
# all other elements are zeros.
# if we don't specify the datatype then it will defaultly take float dtype for elements.

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,

In [18]:
np.random.rand(3,3)
# this method generates an array of random numbers of 3 X 3 matrix and the range of numbers would between 0 and 1.
# this distribution is called "uniform distribution."

array([[0.07298966, 0.02294628, 0.58993842],
       [0.41211608, 0.64252917, 0.4351436 ],
       [0.79108268, 0.0885347 , 0.12248774]])

In [19]:
np.random.randn(3,3)
# this method generates an array of random number of 3 X 3 matrix and
# now this time this matrix consists of (+ve) and (-ve) values and as well there is number which is more than 1.
# this distribution is called "standard normal distribution."

array([[ 1.64941612,  0.50953596, -0.0081014 ],
       [-0.40040762, -1.70904499, -0.82262255],
       [-1.47971439, -1.59327304,  0.09338196]])

In [20]:
np.random.randint(58,70)
# this method gives a random number ranging between its arguments.

59

In [21]:
rand_arr=np.random.randint(12,48,300)
# this method generates output array of integer numbers between the (arg1) and ((arg2)-1).
# the number of the elements in the output array is based on the 3rd argument of the method.
# here the 3rd argument is 300 so output is 300 random elements between 12 to 48-1=47.

In [22]:
rand_arr

array([38, 21, 23, 23, 39, 27, 16, 26, 26, 13, 20, 23, 18, 39, 46, 26, 34,
       24, 13, 36, 17, 47, 32, 46, 26, 24, 27, 38, 21, 18, 40, 12, 12, 47,
       34, 13, 15, 15, 30, 23, 20, 34, 44, 33, 36, 38, 46, 25, 39, 28, 23,
       22, 38, 25, 18, 46, 17, 36, 21, 18, 46, 22, 15, 18, 23, 16, 31, 37,
       45, 14, 41, 28, 46, 45, 37, 16, 17, 41, 30, 42, 44, 34, 28, 41, 16,
       45, 24, 45, 15, 19, 32, 42, 40, 38, 12, 29, 30, 39, 31, 31, 42, 27,
       36, 36, 45, 17, 24, 21, 21, 28, 46, 21, 20, 17, 46, 12, 19, 19, 33,
       29, 13, 13, 15, 44, 17, 41, 42, 17, 26, 37, 30, 46, 16, 45, 29, 41,
       37, 41, 35, 12, 31, 18, 43, 23, 12, 35, 37, 44, 31, 21, 42, 35, 38,
       30, 31, 16, 29, 34, 39, 17, 21, 26, 18, 39, 37, 39, 33, 19, 22, 41,
       21, 13, 24, 12, 18, 37, 13, 35, 20, 20, 33, 34, 32, 37, 17, 35, 46,
       31, 17, 37, 31, 22, 33, 46, 47, 21, 24, 44, 18, 30, 33, 46, 41, 40,
       16, 36, 39, 22, 13, 36, 47, 20, 18, 37, 32, 36, 18, 32, 23, 22, 25,
       39, 38, 33, 31, 29

In [23]:
rand_arr.reshape(30,10)
# this method reshapes or changes the above 300 elements into 30 X 10 matrix.

array([[38, 21, 23, 23, 39, 27, 16, 26, 26, 13],
       [20, 23, 18, 39, 46, 26, 34, 24, 13, 36],
       [17, 47, 32, 46, 26, 24, 27, 38, 21, 18],
       [40, 12, 12, 47, 34, 13, 15, 15, 30, 23],
       [20, 34, 44, 33, 36, 38, 46, 25, 39, 28],
       [23, 22, 38, 25, 18, 46, 17, 36, 21, 18],
       [46, 22, 15, 18, 23, 16, 31, 37, 45, 14],
       [41, 28, 46, 45, 37, 16, 17, 41, 30, 42],
       [44, 34, 28, 41, 16, 45, 24, 45, 15, 19],
       [32, 42, 40, 38, 12, 29, 30, 39, 31, 31],
       [42, 27, 36, 36, 45, 17, 24, 21, 21, 28],
       [46, 21, 20, 17, 46, 12, 19, 19, 33, 29],
       [13, 13, 15, 44, 17, 41, 42, 17, 26, 37],
       [30, 46, 16, 45, 29, 41, 37, 41, 35, 12],
       [31, 18, 43, 23, 12, 35, 37, 44, 31, 21],
       [42, 35, 38, 30, 31, 16, 29, 34, 39, 17],
       [21, 26, 18, 39, 37, 39, 33, 19, 22, 41],
       [21, 13, 24, 12, 18, 37, 13, 35, 20, 20],
       [33, 34, 32, 37, 17, 35, 46, 31, 17, 37],
       [31, 22, 33, 46, 47, 21, 24, 44, 18, 30],
       [33, 46, 41, 

In [24]:
rand_arr.reshape(10,20)

ValueError: ignored

why error ? because there are 300 elements in the (rand_arr) array and we are adjusting these 300 elements into 10 X 20 matrix.
10 X 20 matrix means it can hold only 10X20=200 elements. but we have 300 elements.
so this is throwing error.

In [25]:
rand_arr.max()
# it shows the max value of the (rand_arr) array

47

In [26]:
rand_arr.min()
# it shows the min value of the (rand_arr) array

12

In [27]:
rand_arr.argmax()
# it shows the index of max value of the (rand_arr) array according reshaped array

21

In [28]:
rand_arr.argmin()
# it shows the index of min value of the (rand_arr) array according reshaped array

31

In [29]:
a=np.eye(3)

In [30]:
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
a=np.eye(3,5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [32]:
a.T
# here T is 'transpose of matrix "a".'

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [33]:
a=np.arange(102,201)

In [34]:
a

array([102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114,
       115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127,
       128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140,
       141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153,
       154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166,
       167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179,
       180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192,
       193, 194, 195, 196, 197, 198, 199, 200])

In [35]:
a[2:10]
# above operation is called slicing operation. this operation is based on indexing of the arrays.
# the value of last index number after the colon (:) is not included when taking output.

array([104, 105, 106, 107, 108, 109, 110, 111])

In [36]:
a[6:40]=0
a
# by this operation we can change the values of specific index number value.
# this operation shows the muatability of an array that means we can change values.

array([102, 103, 104, 105, 106, 107,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153,
       154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166,
       167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179,
       180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192,
       193, 194, 195, 196, 197, 198, 199, 200])

In [37]:
a[:]=0
a
# this opeartion shows we can change values of every element at once.

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# **2D Arrays**

In [38]:
two_D_array=np.array([[1,2,3],[6,7,5,],[10,12,12]])
two_D_array

array([[ 1,  2,  3],
       [ 6,  7,  5],
       [10, 12, 12]])

In [39]:
two_D_array[2,2]
# in the above operation the arguments we have given are the index number of [rows, columns].
# Ist argument is the index of row and IInd argument is the index of columns.
# the ouput which is generate is based on these index number rows and columns.

12

In [40]:
two_D_array[2,:]
# here colon represents the values of whole column of same row we specified the index.

array([10, 12, 12])

In [41]:
two_D_array[1]
# if we specify only one argument then the method self decides this as the index of row and gives output accordingly.

array([6, 7, 5])

In [42]:
two_D_array[:,2]
# here colon (:) represents the value of whole row of the same column we specified the index.

array([ 3,  5, 12])

In [43]:
two_D_array[:,(2,1)]
# here colon (:) represents the values of whole matrix and
# in the parenthesis, numbers we specified represents the index number of columns.
# ab jese hamne 2 index no. waley column ko phle likha hai to 2 index no. wala column hi sabse phle output pe print hoga

array([[ 3,  2],
       [ 5,  7],
       [12, 12]])

In [44]:
two_D_array[:]
# if we only specify colon then it will gives all the rows and columns values as it is stored in the array.

array([[ 1,  2,  3],
       [ 6,  7,  5],
       [10, 12, 12]])

In [45]:
two_D_array=np.arange(5,63,2)

In [46]:
two_D_array

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37,
       39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61])

In [47]:
two_D_array+two_D_array
# isse hua ye hai ki array ki sari value khud se hi add hoker print huio hain.

array([ 10,  14,  18,  22,  26,  30,  34,  38,  42,  46,  50,  54,  58,
        62,  66,  70,  74,  78,  82,  86,  90,  94,  98, 102, 106, 110,
       114, 118, 122])

In [48]:
np.exp(two_D_array)
# this method gives the exponential value of every element in the array.

array([1.48413159e+02, 1.09663316e+03, 8.10308393e+03, 5.98741417e+04,
       4.42413392e+05, 3.26901737e+06, 2.41549528e+07, 1.78482301e+08,
       1.31881573e+09, 9.74480345e+09, 7.20048993e+10, 5.32048241e+11,
       3.93133430e+12, 2.90488497e+13, 2.14643580e+14, 1.58601345e+15,
       1.17191424e+16, 8.65934004e+16, 6.39843494e+17, 4.72783947e+18,
       3.49342711e+19, 2.58131289e+20, 1.90734657e+21, 1.40934908e+22,
       1.04137594e+23, 7.69478527e+23, 5.68572000e+24, 4.20121040e+25,
       3.10429794e+26])

In [49]:
np.sqrt(two_D_array)
# this method gives the square root of every element in the array

array([2.23606798, 2.64575131, 3.        , 3.31662479, 3.60555128,
       3.87298335, 4.12310563, 4.35889894, 4.58257569, 4.79583152,
       5.        , 5.19615242, 5.38516481, 5.56776436, 5.74456265,
       5.91607978, 6.08276253, 6.244998  , 6.40312424, 6.55743852,
       6.70820393, 6.8556546 , 7.        , 7.14142843, 7.28010989,
       7.41619849, 7.54983444, 7.68114575, 7.81024968])

In [50]:
np.log(two_D_array)

array([1.60943791, 1.94591015, 2.19722458, 2.39789527, 2.56494936,
       2.7080502 , 2.83321334, 2.94443898, 3.04452244, 3.13549422,
       3.21887582, 3.29583687, 3.36729583, 3.4339872 , 3.49650756,
       3.55534806, 3.61091791, 3.66356165, 3.71357207, 3.76120012,
       3.80666249, 3.8501476 , 3.8918203 , 3.93182563, 3.97029191,
       4.00733319, 4.04305127, 4.07753744, 4.11087386])

In [51]:
np.max(two_D_array)

61

In [52]:
np.min(two_D_array)

5

In [53]:
np.argmax(two_D_array)

28

In [54]:
np.argmin(two_D_array)

0

In [55]:
np.square(two_D_array)

array([  25,   49,   81,  121,  169,  225,  289,  361,  441,  529,  625,
        729,  841,  961, 1089, 1225, 1369, 1521, 1681, 1849, 2025, 2209,
       2401, 2601, 2809, 3025, 3249, 3481, 3721])

In [56]:
np.std(two_D_array)
# standard daviation of the matrix

16.73320053068151

In [57]:
np.var(two_D_array)
# variance of the matrix.

280.0

In [58]:
np.mean(two_D_array)

33.0

In [59]:
std_nrml=np.random.randn(2,4)
std_nrml
# randn() shows the values of -ve, +ve and above 1
# the arguments given in the method represents the no. of rows and columns of the matrix.

array([[-0.90952986, -0.62159557,  1.64148566, -1.29673278],
       [-2.28463397, -0.66202787,  2.57918405, -0.04651618]])

In [60]:
np.round(std_nrml, decimals=2)
# this method is used to rounding off the numbers and specifying the decimal number we decide that how many decimal places
# we want to round off the number.

array([[-0.91, -0.62,  1.64, -1.3 ],
       [-2.28, -0.66,  2.58, -0.05]])

In [61]:
details=np.array(['mayank','bahjoi','abhay','mayank','amroha','adarsh','moradabad','amroha'])
np.unique(details)

array(['abhay', 'adarsh', 'amroha', 'bahjoi', 'mayank', 'moradabad'],
      dtype='<U9')

here in dtype='<u9', it shows that all the string values are less than 9 characters or equal to 9 characters.

# **Pandas**

In the previous session we hav already defined dataset, we are just importiong that dataset and working on it.
But now here we are creating datasets.
when we are supposed to create only one column in any dataset then we use "pd.Series" and if we are supposed to create multiple columns in any dataset then we use "pd.DataFrames" .

In [62]:
import pandas as pd

In [63]:
games1=pd.Series([101,202,303,404,505],index=['cricket','basketball','baseball','football','golf'])
games1
# this method generates a single column dataset in which numeric value is the value which stored in series's single column and
# index value is serial number types value.
# if we don't specify index value then series method will automatically takes index of (0,1,2,3,4,5,6.....) as serial number.

cricket       101
basketball    202
baseball      303
football      404
golf          505
dtype: int64

In [64]:
games1['cricket']

101

In [65]:
games2=pd.Series([10,20,30,40,50,60],index=['chess','carrom','baseball','golf','cricket','freefire'])
games2

chess       10
carrom      20
baseball    30
golf        40
cricket     50
freefire    60
dtype: int64

In [66]:
games1+games2

baseball      333.0
basketball      NaN
carrom          NaN
chess           NaN
cricket       151.0
football        NaN
freefire        NaN
golf          545.0
dtype: float64

here NaN values are showing because jo bhi index value (serial number) dono series mein same hain unki values add ho gayi aur jo nahi hain unki values add na hoke NaN show ho gaya hai

In [67]:
df1=pd.DataFrame(np.random.rand(6,3), index='a b c d e f'.split(), columns='score1 score2 score3'.split())
df1
# here we are creating random values for our dataset using 'np.random.rand(no. of rows, no. of columns)' method.
# creating searial number using index.
# creating column names for our dataset using columns variable
# most important we use .split() method to split all the rows and columns names because we didn't declare each row and column
# as separate array that's why.
# index and column values are depend on the argument list of random.rand() method.
# ---------------------------------------------------------------------------------------------------------------------------- #
# no. of rows = index values
# no. of columns = columns values

score1    score2    score3
a  0.013675  0.030788  0.193613
b  0.306546  0.293641  0.637967
c  0.004082  0.361532  0.206718
d  0.899890  0.418351  0.072796
e  0.272644  0.941280  0.080124
f  0.737001  0.303922  0.389962

In [68]:
df1["score1"]

a    0.013675
b    0.306546
c    0.004082
d    0.899890
e    0.272644
f    0.737001
Name: score1, dtype: float64

In [69]:
df1[['score1', 'score2']]

score1    score2
a  0.013675  0.030788
b  0.306546  0.293641
c  0.004082  0.361532
d  0.899890  0.418351
e  0.272644  0.941280
f  0.737001  0.303922

In [70]:
df1['score4']=df1['score1']*df1['score2']
df1

score1    score2    score3    score4
a  0.013675  0.030788  0.193613  0.000421
b  0.306546  0.293641  0.637967  0.090014
c  0.004082  0.361532  0.206718  0.001476
d  0.899890  0.418351  0.072796  0.376470
e  0.272644  0.941280  0.080124  0.256634
f  0.737001  0.303922  0.389962  0.223991

In [71]:
# we can create dataset using dictionary data-structure
df2={
    'name':['mayank','abhay','adarsh','mukul','pradeep'],
    'address':['bahjoi','amroha','moradabad','rampur','rampur']
}
df=pd.DataFrame(df2)
df
# here data before colon(:) is name of column i.e., name and address and data after colon(:) is the actual data of table.

name    address
0   mayank     bahjoi
1    abhay     amroha
2   adarsh  moradabad
3    mukul     rampur
4  pradeep     rampur

In [72]:
df['name']

0     mayank
1      abhay
2     adarsh
3      mukul
4    pradeep
Name: name, dtype: object

In [73]:
df[['name','address']]
# jab ek se jada columns ko print krna ho ya fetch krna ho to double large brackets ka use krte hain.

name    address
0   mayank     bahjoi
1    abhay     amroha
2   adarsh  moradabad
3    mukul     rampur
4  pradeep     rampur

In [74]:
df=df.drop('name',axis=1)
# axis defines whether you want to delete data column-wise or row-wise.
# hee in the above method we define axis=1 that means we want to data column-wise.

In [75]:
df

address
0     bahjoi
1     amroha
2  moradabad
3     rampur
4     rampur

In [76]:
df=df.drop(2,axis=0)
# if we didn't specify any axis by default it is axis=0 that means we are deleting data row-wise.

In [77]:
df

address
0  bahjoi
1  amroha
3  rampur
4  rampur

In [78]:
df=df.drop(4)
df

address
0  bahjoi
1  amroha
3  rampur